/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
    

Robo a = new Robo("RoboA", 5, 32, "O", 31);


System.out.println(a.coordenadaAtual());
System.out.println(a.roboApontando());
System.out.println(a.girarRobo("E"));
System.out.println(a.valorBateria());
System.out.println(a.moverRobo(10));
System.out.println(a.valorBateria());























    }
}
