/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

        Drone a = new Drone("a", 30, true, true);
        a.droneDecola();
        a.droneDireita();
        a.droneSobe(50);
        a.droneDesce(10);
        a.droneFrente(100);
        a.droneAtras(30);
        a.droneDireita();
        a.droneEsquerda();
        a.coordenadaDoDroneAtual();
        a.cargaBateriaAtual();
        a.droneFrente(100);
        a.droneRetorna();

        Drone b = new Drone("b", 50, 1, false, true);
        a.droneDecola();
        a.droneDireita();
        a.droneSobe(50);
        a.droneDesce(10);
        a.droneFrente(100);
        a.droneAtras(30);
        a.droneDireita();
        a.droneEsquerda();
        a.coordenadaDoDroneAtual();
        a.cargaBateriaAtual();
        a.droneFrente(100);
        a.droneRetorna();

        Drone c = new Drone("c", 30, 2, true, false);
        a.droneDecola();
        a.droneDireita();
        a.droneSobe(50);
        a.droneDesce(10);
        a.droneFrente(100);
        a.droneAtras(30);
        a.droneDireita();
        a.droneEsquerda();
        a.coordenadaDoDroneAtual();
        a.cargaBateriaAtual();
        a.droneFrente(100);
        a.droneRetorna();
    }
}
