/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    

        Drone a = new Drone("A", 90, true, true);
        Drone b = new Drone("b", 10, false, false);


    @Test
    void testeCargaBAteria() {

       assertEquals(90, a.cargaBateriaAtual());
        assertEquals(10,b.cargaBateriaAtual());
    }

}
