/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import edu.princeton.cs.algs4.Draw;

public class App {

    private Draw desenho;
    private Relogio[] vetorRelogio = new Relogio[2];

    public App() {
        this.desenho = new Draw();
        // definindo a área de desenho --
        // https://introcs.cs.princeton.edu/java/stdlib/javadoc/Draw.html
        this.desenho.setCanvasSize(800, 800);
        // definindo a escala da área de desenho -- leia mais na documentação da classe
        this.desenho.setXscale(0, 800);
        this.desenho.setYscale(0, 800);
    }

    public boolean adicionarRelogio(Relogio consulta) {
        for (int i = 0; i < 2; i++) {
            if (this.vetorRelogio[i] == null) {
                this.vetorRelogio[i] = consulta;
                return true;
            }
        }
        // caso não seja possivel adicionar mais relogios, retorna falso
        return false;
    }

    public void desenharRelogiosNoTerminal() {
        for (int i = 0; i < 2; i++) {
            System.out.println(this.vetorRelogio[i].horaMinutoSegundo(17, 30, 45));

        }
    }

    public void desenharRelogiosGui() {
        for (int i = 0; i < 2; i++) {
            this.vetorRelogio[i].desenha(this.desenho, 12, 30, 45);
        }
    }

    public static void main(String[] args) {
        Relogio primeiroRelogio = new Relogio("Londres", 0, 200, 400);
        Relogio segundoRelogio = new Relogio("ddd", 1, 500, 400);
        Relogio terceiroRelogio = new Relogio("ccc", 1, 350, 600);

        App tela = new App();
        tela.adicionarRelogio(primeiroRelogio);
        tela.adicionarRelogio(segundoRelogio);
        tela.adicionarRelogio(terceiroRelogio);

        tela.desenharRelogiosGui();
        tela.desenharRelogiosNoTerminal();

    }
}